/**
*
*
*/
CREATE DATABASE IF NOT EXISTS BROWLING_RESERVE;

/**
*
*
*/
USE BROWLING_RESERVE;

/**
*
*
*/
CREATE TABLE IF NOT EXISTS CLIENTE(
	ID INT UNSIGNED AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CELULAR VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(70) NOT NULL,
    PRIMARY KEY (ID)
);

/**
*
*
*/
CREATE TABLE IF NOT EXISTS ENDERECO(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLIENT_ID INT UNSIGNED NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL DEFAULT 'SP',
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES CLIENT (ID)
);


/**
*
*
*/
CREATE TABLE IF NOT EXISTS USUARIO(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(20) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

/**
*
*
*/
CREATE TABLE IF NOT EXISTS RESERVA(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLIENTE_ID INT NOT NULL,
    DATA_RESERVA DATE NOT NULL,
    HORARIO_RESERVA VARCHAR(5) NOT NULL,
    QTD_PISTAS_RESERVA INT(3) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES USUARIO (ID)
);
